// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RazorTest.Data;

#nullable disable

namespace RazorTest.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260305114551_1")]
    partial class _1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.2");

            modelBuilder.Entity("RazorTest.Models.Queue", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("QueueName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Queues");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            QueueName = "Serverside"
                        },
                        new
                        {
                            Id = 2,
                            QueueName = "Gui-programmering"
                        },
                        new
                        {
                            Id = 3,
                            QueueName = "Intro"
                        });
                });

            modelBuilder.Entity("RazorTest.Models.QueueEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("QueueId")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("StudentId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("TeacherId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("StudentId");

                    b.HasIndex("TeacherId");

                    b.HasIndex("QueueId", "StudentId")
                        .IsUnique();

                    b.ToTable("QueueEntries");
                });

            modelBuilder.Entity("RazorTest.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("TeacherQueues", b =>
                {
                    b.Property<int>("QueueId")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("TeacherId")
                        .HasColumnType("TEXT");

                    b.HasKey("QueueId", "TeacherId");

                    b.HasIndex("TeacherId");

                    b.ToTable("TeacherQueues", (string)null);

                    b.HasData(
                        new
                        {
                            QueueId = 1,
                            TeacherId = new Guid("81cce9d1-dd44-4754-b3b7-f150cdd4ff11")
                        },
                        new
                        {
                            QueueId = 2,
                            TeacherId = new Guid("11111111-1111-1111-1111-111111111111")
                        },
                        new
                        {
                            QueueId = 3,
                            TeacherId = new Guid("81cce9d1-dd44-4754-b3b7-f150cdd4ff11")
                        },
                        new
                        {
                            QueueId = 3,
                            TeacherId = new Guid("11111111-1111-1111-1111-111111111111")
                        });
                });

            modelBuilder.Entity("RazorTest.Models.Student", b =>
                {
                    b.HasBaseType("RazorTest.Models.User");

                    b.ToTable("Students");

                    b.HasData(
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222222"),
                            Email = "elev1@techcollege.dk",
                            Name = "Elev 1",
                            PasswordHash = "U3R1ZGVudDEyMzQ="
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333333"),
                            Email = "elev2@techcollege.dk",
                            Name = "Elev 2",
                            PasswordHash = "U3R1ZGVudDEyMzQ="
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-444444444444"),
                            Email = "elev3@techcollege.dk",
                            Name = "Elev 3",
                            PasswordHash = "U3R1ZGVudDEyMzQ="
                        },
                        new
                        {
                            Id = new Guid("55555555-5555-5555-5555-555555555555"),
                            Email = "elev4@techcollege.dk",
                            Name = "Elev 4",
                            PasswordHash = "U3R1ZGVudDEyMzQ="
                        },
                        new
                        {
                            Id = new Guid("66666666-6666-6666-6666-666666666666"),
                            Email = "elev5@techcollege.dk",
                            Name = "Elev 5",
                            PasswordHash = "U3R1ZGVudDEyMzQ="
                        });
                });

            modelBuilder.Entity("RazorTest.Models.Teacher", b =>
                {
                    b.HasBaseType("RazorTest.Models.User");

                    b.ToTable("Teachers");

                    b.HasData(
                        new
                        {
                            Id = new Guid("81cce9d1-dd44-4754-b3b7-f150cdd4ff11"),
                            Email = "test@gmail.com",
                            Name = "Test",
                            PasswordHash = "VGVzdDEyMzQ="
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111111"),
                            Email = "amalie@techcollege.dk",
                            Name = "Amalie",
                            PasswordHash = "VGVhY2hlcjEyMzQ="
                        });
                });

            modelBuilder.Entity("RazorTest.Models.QueueEntry", b =>
                {
                    b.HasOne("RazorTest.Models.Queue", "Queue")
                        .WithMany("QueueEntries")
                        .HasForeignKey("QueueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RazorTest.Models.Student", "Student")
                        .WithMany("QueueEntries")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RazorTest.Models.Teacher", "Teacher")
                        .WithMany("QueueEntries")
                        .HasForeignKey("TeacherId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Queue");

                    b.Navigation("Student");

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("TeacherQueues", b =>
                {
                    b.HasOne("RazorTest.Models.Queue", null)
                        .WithMany()
                        .HasForeignKey("QueueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RazorTest.Models.Teacher", null)
                        .WithMany()
                        .HasForeignKey("TeacherId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RazorTest.Models.Student", b =>
                {
                    b.HasOne("RazorTest.Models.User", null)
                        .WithOne()
                        .HasForeignKey("RazorTest.Models.Student", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RazorTest.Models.Teacher", b =>
                {
                    b.HasOne("RazorTest.Models.User", null)
                        .WithOne()
                        .HasForeignKey("RazorTest.Models.Teacher", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RazorTest.Models.Queue", b =>
                {
                    b.Navigation("QueueEntries");
                });

            modelBuilder.Entity("RazorTest.Models.Student", b =>
                {
                    b.Navigation("QueueEntries");
                });

            modelBuilder.Entity("RazorTest.Models.Teacher", b =>
                {
                    b.Navigation("QueueEntries");
                });
#pragma warning restore 612, 618
        }
    }
}
